import assert from 'node:assert/strict';
import {execFile} from 'node:child_process';
import {access, readFile} from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import {promisify} from 'node:util';
import {parse, stringify} from 'yaml';
import {FIXTURE_SOURCES, quarantineFixture} from './helpers/quarantine-fixture.mjs';

const exec = promisify(execFile);
const essManifest = await readFile(path.join(import.meta.dirname, 'fixtures', 'ess-v5.yaml'), 'utf8');
const categories = ['Start here', 'Concepts', 'Guides', 'Reference', 'Examples', 'Project status'];

function essFiles(manifestText) {
  const [surface] = parse(manifestText).surfaces;
  const {navigation} = surface.source;
  const leaves = (items) => items.flatMap((item) => (typeof item === 'string' ? [item] : leaves(item.items)));
  const documents = [...new Set([...leaves(navigation.sidebar), ...(navigation.menuWithheld ?? []), ...(navigation.landing ? [navigation.landing] : [])])];
  return Object.fromEntries([
    ...documents.map((document) => [`website/${document}`, `# ${document}\n\nThe ${document} page of the ESS fixture.\n`]),
    ['website/static/img/mark.svg', '<svg xmlns="http://www.w3.org/2000/svg"/>\n'],
    ['website/blog/2026-09-01-field-note.md', '# A field note\n\nThe ESS fixture field note.\n'],
  ]);
}

function sourcesWith(manifestText, files = essFiles(manifestText)) {
  return [...FIXTURE_SOURCES, {repository: 'ess', manifest: manifestText, files}]
    .sort((left, right) => (left.repository < right.repository ? -1 : 1));
}

function environmentFor(fixture) {
  const environment = {...process.env, B10X_DOCS_SOURCE_SET: fixture.sourceSetPath};
  delete environment.B10X_BOOTSTRAP_FIXTURE;
  delete environment.B10X_SOURCE_WORKSPACE;
  delete environment.B10X_GENERATION_LEASE_TOKEN;
  return environment;
}

async function prepare(context, sources) {
  const fixture = await quarantineFixture(context, {sources});
  await exec(process.execPath, ['scripts/prepare-site.mjs'], {cwd: fixture.websiteRoot, env: environmentFor(fixture)});
  const generated = path.join(fixture.websiteRoot, '.generated');
  const sidebars = await readFile(path.join(generated, 'sidebars.cjs'), 'utf8');
  return {generated, sidebars: JSON.parse(sidebars.replace(/^module\.exports = /, '').replace(/;\n$/, ''))};
}

const exists = (file) => access(file).then(() => true, () => false);

function withNavigation(manifestText, change) {
  const manifest = parse(manifestText);
  change(manifest.surfaces[0].source.navigation);
  return stringify(manifest);
}

test('a v5 ESS bundle declaring its sidebar prepares a site with its six categories and its landing at /docs/ess/', async (context) => {
  const {generated, sidebars} = await prepare(context, sourcesWith(essManifest));
  const section = sidebars.project_ess[2];
  assert.deepEqual(section.items.map((category) => category.label), categories);
  assert.deepEqual(section.items[0].items, [{type: 'doc', id: 'ess/index'}, {type: 'doc', id: 'ess/getting-started/index'}]);
  assert.deepEqual(sidebars.project_harness[2].items, [{type: 'autogenerated', dirName: 'harness'}]);

  // Every declared leaf is a document the build writes, at the path Docusaurus reads that id from.
  const ids = JSON.stringify(section.items).match(/"id":"[^"]+"/g).map((match) => match.slice(6, -1));
  for (const id of ids) assert.ok(await exists(path.join(generated, 'docs', `${id}.md`)), `${id} is generated`);

  const landing = await readFile(path.join(generated, 'docs', 'ess', 'index.md'), 'utf8');
  assert.match(landing, /^slug: "\/ess\/"$/m);
  assert.match(landing, /The docs\/index\.md page of the ESS fixture\./);
  assert.doesNotMatch(landing, /Source-owned documentation ·/, 'the generated surface profile is not written');

  const withheld = path.join(generated, 'docs', 'menu.withheld', 'ess', 'guides', 'record-realization', 'index.md');
  assert.match(await readFile(withheld, 'utf8'), /^slug: "\/ess\/guides\/record-realization\/"$/m, 'a withheld document keeps its route');
  assert.equal(await exists(path.join(generated, 'docs', 'ess', 'guides', 'record-realization')), false, 'and sits outside every autogenerated directory');
  assert.doesNotMatch(JSON.stringify(sidebars), /record-realization/);
});

test('a landing document other than the index replaces the generated profile at the route base', async (context) => {
  const manifest = withNavigation(essManifest, (navigation) => {
    navigation.landing = 'docs/getting-started.md';
    navigation.sidebar[0].items = ['docs/getting-started.md'];
  });
  const {generated, sidebars} = await prepare(context, sourcesWith(manifest));
  const landing = await readFile(path.join(generated, 'docs', 'ess', 'index.md'), 'utf8');
  assert.match(landing, /^slug: "\/ess\/"$/m);
  assert.match(landing, /The docs\/getting-started\.md page of the ESS fixture\./);
  assert.doesNotMatch(landing, /Source-owned documentation ·/);
  assert.equal(await exists(path.join(generated, 'docs', 'ess', 'getting-started')), false, 'the landing is served once, at the route base');
  assert.deepEqual(sidebars.project_ess[2].items[0].items, [{type: 'doc', id: 'ess/index'}]);
});

test('a landing document and an index document that both claim the route base are refused by name', async (context) => {
  const manifest = withNavigation(essManifest, (navigation) => {
    navigation.landing = 'docs/getting-started.md';
  });
  await assert.rejects(prepare(context, sourcesWith(manifest)), (error) => {
    assert.match(String(error.stderr), /ess\/docs landing docs\/getting-started\.md and website\/docs\/index\.md both serve \/docs\/ess\//);
    return true;
  });
});

test('menu-withheld documents stay out of an autogenerated sidebar too', async (context) => {
  const manifest = withNavigation(essManifest, (navigation) => {
    navigation.sidebar = 'autogenerated';
  });
  const {generated, sidebars} = await prepare(context, sourcesWith(manifest, essFiles(essManifest)));
  assert.deepEqual(sidebars.project_ess[2].items, [{type: 'autogenerated', dirName: 'ess'}]);
  assert.ok(await exists(path.join(generated, 'docs', 'menu.withheld', 'ess', 'guides', 'record-realization', 'index.md')));
  assert.equal(await exists(path.join(generated, 'docs', 'ess', 'guides', 'record-realization')), false);
  assert.ok(await exists(path.join(generated, 'docs', 'ess', 'guides', 'track-change', 'index.md')));
});
