import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import {readManifest} from '@beyond10x/docs-system/manifest';
import {declaredDocumentRoute, documentIdForRoute, renderSidebars} from '../scripts/sidebar-contract.mjs';

const fixtures = path.join(import.meta.dirname, 'fixtures');
const sidebarsOf = (source) => JSON.parse(source.replace(/^module\.exports = /, '').replace(/;\n$/, ''));

async function essV5() {
  // Docs System's own v5 rendering of ESS's curated website/sidebars.ts, read through its validator.
  return readManifest(path.join(fixtures, 'ess-v5.yaml'));
}

function registryFor(manifests) {
  return {surfaces: manifests.map((manifest) => ({name: manifest.repository.displayName ?? manifest.repository.id, repository: {id: manifest.repository.id}}))};
}

const harness = {
  schema: 'b10x-docs/v4',
  repository: {id: 'harness', displayName: 'Harness'},
  surfaces: [{id: 'docs', routeBase: '/docs/harness/', source: {root: '.', navigation: {group: 'Build', label: 'Harness', order: 0, sidebar: 'autogenerated'}}}],
};

test('a declared ESS sidebar renders its six categories, in order, as documents of the one docs instance', async () => {
  const ess = await essV5();
  const document = sidebarsOf(renderSidebars(registryFor([ess, harness]), [ess, harness]));
  const [outcome, allDocs, section] = document.project_ess;
  assert.deepEqual(outcome, {type: 'link', label: 'Start by outcome', href: '/start/'});
  assert.deepEqual(allDocs, {type: 'link', label: 'All technical docs', href: '/docs/'});
  assert.equal(section.label, 'ESS');
  assert.deepEqual(section.link, {type: 'doc', id: 'ess/index'});
  assert.deepEqual(section.items.map((category) => category.label), ['Start here', 'Concepts', 'Guides', 'Reference', 'Examples', 'Project status']);
  assert.ok(section.items.every((category) => category.type === 'category' && category.collapsed === false));
  assert.deepEqual(section.items[0].items, [
    {type: 'doc', id: 'ess/index'},
    {type: 'doc', id: 'ess/getting-started/index'},
  ]);
  assert.deepEqual(section.items[2].items.map((item) => item.id), [
    'ess/guides/write-a-specification/index',
    'ess/guides/generate-artifacts/index',
    'ess/guides/verify-conformance/index',
    'ess/guides/track-change/index',
    'ess/guides/synthesize/index',
    'ess/guides/check-infrastructure/index',
  ]);
  assert.deepEqual(section.items[4].items, [{type: 'doc', id: 'ess/examples/specification-to-contracts/index'}]);
  const serialized = JSON.stringify(document.project_ess);
  assert.doesNotMatch(serialized, /autogenerated/, 'a declared sidebar replaces the autogenerated entry');
  assert.doesNotMatch(serialized, /record-realization/, 'a menu-withheld document is left out of the tree');
  assert.deepEqual(document.project_harness[2].items, [{type: 'autogenerated', dirName: 'harness'}], 'an undeclared repository beside it is untouched');
});

test('a repository with no declared sidebar renders the same sidebars.cjs bytes as before', async () => {
  // Captured from website ea48ffa's renderSidebars over the same input: 26 v3/v4 sources and the front door.
  const {registry, manifests} = JSON.parse(await readFile(path.join(fixtures, 'sidebars-undeclared.input.json'), 'utf8'));
  const before = await readFile(path.join(fixtures, 'sidebars-undeclared.cjs'), 'utf8');
  assert.equal(renderSidebars(registry, manifests), before);
});

test('a declared landing document is served at the route base, and every other document keeps its route', async () => {
  const ess = await essV5();
  const [surface] = ess.surfaces;
  assert.equal(declaredDocumentRoute(surface, 'docs/index.md'), '/docs/ess/');
  assert.equal(declaredDocumentRoute(surface, 'docs/concepts/overview.md'), '/docs/ess/concepts/overview/');
  const landingElsewhere = {...surface, source: {...surface.source, navigation: {...surface.source.navigation, landing: 'docs/getting-started.md'}}};
  assert.equal(declaredDocumentRoute(landingElsewhere, 'docs/getting-started.md'), '/docs/ess/');
  assert.equal(declaredDocumentRoute(landingElsewhere, 'docs/concepts/overview.md'), '/docs/ess/concepts/overview/');
  const undeclared = {routeBase: '/docs/harness/', source: {root: '.', navigation: {sidebar: 'autogenerated'}}};
  assert.equal(declaredDocumentRoute(undeclared, 'docs/getting-started.md'), '/docs/harness/getting-started/');
  assert.equal(declaredDocumentRoute(undeclared, 'README.md'), '/docs/harness/');

  const declared = {...landingElsewhere, source: {...landingElsewhere.source, navigation: {
    ...landingElsewhere.source.navigation,
    sidebar: [{label: 'Start here', items: ['docs/concepts/overview.md', 'docs/getting-started.md']}],
  }}};
  const manifest = {...ess, surfaces: [declared]};
  const document = sidebarsOf(renderSidebars(registryFor([manifest]), [manifest]));
  assert.deepEqual(document.project_ess[2].items, [{
    type: 'category',
    label: 'Start here',
    items: [{type: 'doc', id: 'ess/concepts/overview/index'}, {type: 'doc', id: 'ess/index'}],
  }], 'the landing leaf names the document at the route base; an undeclared collapsed state is left to Docusaurus');
});

test('a sidebar leaf names the id Docusaurus assigns the generated file, number prefixes stripped', () => {
  assert.equal(documentIdForRoute('/docs/ess/'), 'ess/index');
  assert.equal(documentIdForRoute('/docs/ess/guides/track-change/'), 'ess/guides/track-change/index');
  assert.equal(documentIdForRoute('/docs/ess/01-intro/02-setup/'), 'ess/intro/setup/index');
  assert.equal(documentIdForRoute('/docs/ess/2026-09-release/'), 'ess/2026-09-release/index');
});

test('declared navigation refusals: route base namespace, declared paths without a document, and a doubled landing route', async () => {
  const {declaredNavigationRefusals} = await import('../scripts/sidebar-contract.mjs');
  const ess = await essV5();
  const document = (relative) => ({repository: 'ess', surface: 'docs', kind: 'document', sourcePath: `website/${relative}`, outputPath: `ess/docs/document/${relative}`});
  const [surface] = ess.surfaces;
  const collected = ['docs/index.md', 'docs/getting-started.md', 'docs/guides/record-realization.md'];
  const leaves = (items) => items.flatMap((item) => (typeof item === 'string' ? [item] : leaves(item.items)));
  const all = [...new Set([...leaves(surface.source.navigation.sidebar), ...collected])].map(document);
  assert.deepEqual(declaredNavigationRefusals(ess, all), []);

  const missing = all.filter((file) => !['website/docs/concepts/ess.md', 'website/docs/guides/record-realization.md'].includes(file.sourcePath));
  assert.deepEqual(declaredNavigationRefusals(ess, missing), [
    'ess/docs sidebar leaf docs/concepts/ess.md is not a collected document',
    'ess/docs menu-withheld document docs/guides/record-realization.md is not a collected document',
  ]);
  const withSurface = (change) => ({...ess, surfaces: [change(structuredClone(surface))]});
  assert.deepEqual(declaredNavigationRefusals(withSurface((s) => ({...s, routeBase: '/docs/harness/ess/'})), all), ['ess/docs routeBase /docs/harness/ess/ is not at or below /docs/ess/']);
  assert.deepEqual(declaredNavigationRefusals(withSurface((s) => ({...s, routeBase: '/docs/ess-extra/'})), all), ['ess/docs routeBase /docs/ess-extra/ is not at or below /docs/ess/']);
  assert.deepEqual(declaredNavigationRefusals(withSurface((s) => ({...s, routeBase: '/docs/ess/lab/'})), all), []);
  const v3 = {schema: 'b10x-docs/v3', repository: {id: 'harness'}, surfaces: [{id: 'docs', routeBase: '/docs/eventlog/', source: {root: '.', documents: {include: ['docs/**']}}}]};
  assert.deepEqual(declaredNavigationRefusals(v3, []), ['harness/docs routeBase /docs/eventlog/ is not at or below /docs/harness/'], 'every manifest revision');
  const website = {schema: 'b10x-docs/v4', repository: {id: 'website'}, surfaces: [{id: 'site', routeBase: '/', source: {root: '.', documents: {include: ['README.md']}}}]};
  assert.deepEqual(declaredNavigationRefusals(website, []), [], "the Website's own / surface is the one exception");
  assert.deepEqual(declaredNavigationRefusals({...v3, repository: {id: 'website'}}, []), ['website/docs routeBase /docs/eventlog/ is not at or below /docs/website/']);
  assert.deepEqual(
    declaredNavigationRefusals(withSurface((s) => { s.source.navigation.landing = 'docs/getting-started.md'; return s; }), all),
    ['ess/docs landing docs/getting-started.md and website/docs/index.md both serve /docs/ess/'],
  );
  assert.deepEqual(
    declaredNavigationRefusals(withSurface((s) => { s.source.navigation.landing = 'docs/absent.md'; return s; }), all.filter((file) => file.sourcePath !== 'website/docs/index.md')),
    ['ess/docs sidebar leaf docs/index.md is not a collected document', 'ess/docs landing docs/absent.md is not a collected document'],
  );
});

test('the source preview reports the same declared navigation refusals prepare-site fails on', async () => {
  const preview = await readFile(path.join(import.meta.dirname, '..', 'scripts', 'source-preview-checks.mjs'), 'utf8');
  const preparation = await readFile(path.join(import.meta.dirname, '..', 'scripts', 'prepare-site.mjs'), 'utf8');
  for (const [name, source] of [['source-preview-checks.mjs', preview], ['prepare-site.mjs', preparation]]) {
    assert.match(source, /declaredNavigationRefusals\(/, `${name} applies the shared refusal list`);
    assert.match(source, /documentPagePath\(/, `${name} derives the generated page through the shared function`);
  }
});

test('the document at the route base cannot be menu-withheld, whether it is the index or a declared landing', async () => {
  const {declaredNavigationRefusals, isMenuWithheld} = await import('../scripts/sidebar-contract.mjs');
  const ess = await essV5();
  const [surface] = ess.surfaces;
  const document = (relative) => ({repository: 'ess', surface: 'docs', kind: 'document', sourcePath: `website/${relative}`, outputPath: `ess/docs/document/${relative}`});
  const withNavigation = (change) => {
    const changed = structuredClone(surface);
    change(changed.source.navigation);
    return {...ess, surfaces: [changed]};
  };
  const index = withNavigation((navigation) => {
    delete navigation.landing;
    navigation.menuWithheld = ['docs/index.md'];
    navigation.sidebar = [{label: 'Start here', items: ['docs/getting-started.md']}];
  });
  assert.deepEqual(declaredNavigationRefusals(index, ['docs/index.md', 'docs/getting-started.md'].map(document)), [
    'ess/docs menu-withheld document docs/index.md serves the route base /docs/ess/, which cannot be withheld',
  ]);
  const landing = withNavigation((navigation) => {
    navigation.landing = 'docs/getting-started.md';
    navigation.menuWithheld = ['docs/getting-started.md'];
    navigation.sidebar = [{label: 'Start here', items: ['docs/concepts/overview.md']}];
  });
  assert.deepEqual(declaredNavigationRefusals(landing, ['docs/getting-started.md', 'docs/concepts/overview.md'].map(document)), [
    'ess/docs menu-withheld document docs/getting-started.md serves the route base /docs/ess/, which cannot be withheld',
  ]);
  assert.equal(isMenuWithheld(surface, 'docs/guides/record-realization.md'), true);
  assert.equal(isMenuWithheld(surface, 'docs/index.md'), false);
});
