import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import {buildApiCatalog, describeApiSpecification, renderApiCatalogLanding} from '../scripts/api-catalog.mjs';
import {assertDocumentationFamilyDistribution, documentationFamilies, documentationFamilyOrder, renderSidebars} from '../scripts/sidebar-contract.mjs';
import {normalizePassiveMarkdown, stripManagedRanges} from '../scripts/passive-markdown.mjs';

const root = path.resolve(import.meta.dirname, '..');

test('API discovery is derived from locked specification facts and repository manifests', () => {
  const repositories = [
    ['secrets', 'Secrets', 'Services', 'openapi'],
    ['aep-service', 'AEP Service', 'Services', 'openapi'],
    ['docs-system', 'Docs System', 'Build', 'json-schema'],
    ['devcenter', 'Devcenter', 'Products', 'openapi'],
  ];
  const specifications = repositories.map(([repository, displayName, , kind], index) => describeApiSpecification({
    document: kind === 'openapi'
      ? {openapi: '3.1.0', info: {title: `${displayName} API`, version: `1.0.${index}`}, paths: {'/ready': {get: {}}, '/items': {parameters: [], post: {}}}}
      : {title: 'Manifest schema', type: 'object', properties: {schema: {}, repository: {}}},
    file: {repository, sourcePath: 'contract.json', specificationId: 'contract', kind, route: `/api/${repository}/contract/`},
    manifest: {repository: {id: repository, displayName, url: `https://github.com/beyond10x/${repository}`}},
    commit: String(index).repeat(40),
  }));
  const catalog = buildApiCatalog(specifications);
  assert.equal(catalog.schema, 'b10x-public-api-catalog/v1');
  assert.deepEqual(catalog.repositories.map((repository) => repository.id), ['aep-service', 'devcenter', 'docs-system', 'secrets']);
  assert.equal(catalog.repositories.length, 4);
  assert.equal(catalog.repositories.find((repository) => repository.id === 'aep-service').specifications[0].operationCount, 2);
  assert.equal(catalog.repositories.find((repository) => repository.id === 'docs-system').specifications[0].propertyCount, 2);
  const landing = renderApiCatalogLanding();
  assert.match(landing, /<ApiCatalog catalog=\{catalog\} \/>/);
  assert.match(landing, /\/api-catalog\.json/);
});

test('rendered Markdown removes complete managed documentation ranges without mutating source bytes', () => {
  const source = [
    '# Public README',
    '',
    '<!-- b10x-docs:discovery:start -->',
    '## Documentation',
    '[Self link](https://example.invalid)',
    '<!-- b10x-docs:discovery:end -->',
    '',
    '<!-- b10x-docs:start -->',
    'Generated discovery copy.',
    '<!-- b10x-docs:end -->',
    '',
    '<!-- b10x-docs-operations:start -->',
    'Generated agent operations.',
    '<!-- b10x-docs-operations:end -->',
    '',
    '```md',
    '<!-- b10x-docs:start -->',
    'A documented marker example.',
    '<!-- b10x-docs:end -->',
    '```',
    '',
    '## Kept {#kept}',
  ].join('\n');
  const original = Buffer.from(source);
  const rendered = normalizePassiveMarkdown(source);
  assert.doesNotMatch(rendered, /Self link|Generated discovery copy|Generated agent operations/);
  assert.match(rendered, /A documented marker example/);
  assert.match(rendered, /<a id="kept"><\/a>\n## Kept/);
  assert.deepEqual(Buffer.from(source), original);
  assert.throws(() => stripManagedRanges('<!-- b10x-docs:start -->\nunclosed'), /not closed/);
  assert.throws(() => stripManagedRanges('<!-- b10x-docs:end -->'), /without a start/);
});

test('technical documentation keeps an overview while every project receives one scoped sidebar', () => {
  const repositories = [
    ['principles', 'Principles', 'Foundation'],
    ['runtime', 'Runtime', 'Foundation'],
    ['harness', 'Harness', 'Build'],
    ['worktree', 'Worktree', 'Build'],
    ['identity', 'Identity', 'Services'],
    ['workflow', 'Workflow', 'Services'],
    ['devcenter', 'Devcenter', 'Products'],
  ];
  const registry = {surfaces: [
    {name: 'Start', kind: 'front-door', repository: {id: 'website'}},
    ...repositories.map(([id, name]) => ({name, repository: {id}})),
  ]};
  const manifests = repositories.map(([id, name, group], order) => ({
    repository: {id},
    surfaces: [{source: {navigation: {label: name, group, order, sidebar: 'autogenerated'}}}],
  })).concat([{repository: {id: 'website'}, surfaces: [{source: {navigation: {label: 'Start', order: 0, sidebar: 'flat'}}}]}]);
  const source = renderSidebars(registry, manifests);
  const document = JSON.parse(source.replace(/^module\.exports = /, '').replace(/;\n$/, ''));
  assert.deepEqual(document.docs[0], {type: 'link', label: 'Choose an outcome', href: '/start/'});
  assert.deepEqual(document.docs[1], {type: 'doc', id: 'index', label: 'Technical documentation'});
  assert.deepEqual(document.docs[2], {type: 'link', label: 'Website internals', href: '/docs/website/'});
  assert.ok(document.docs.every((item) => item.label !== 'Start'));
  const families = document.docs.slice(3);
  assert.deepEqual(families.map((family) => family.label), documentationFamilies.map((family) => family.label));
  assert.ok(families.every((family) => family.collapsed && family.link.type === 'doc'));
  assert.deepEqual(families.map((family) => family.link.id), ['families/foundations', 'families/build', 'families/services', 'families/products']);
  assert.ok(families.flatMap((family) => family.items).every((repository) => repository.type === 'link'));
  assert.deepEqual(
    families.flatMap((family) => family.items).map((repository) => repository.href.replace(/^\/docs\//, '').replace(/\/$/, '')).sort(),
    repositories.map(([id]) => id).sort(),
  );
  for (const repository of ['website', ...repositories.map(([id]) => id)]) {
    assert.deepEqual(document[`project_${repository.replaceAll('-', '_')}`], [{type: 'autogenerated', dirName: repository}]);
  }
});

test('the authored family map explains purpose, start, and a valid cross-family next step without owning membership', async () => {
  const taxonomy = JSON.parse(await readFile(path.join(root, 'data/ecosystem-families.json'), 'utf8'));
  assert.equal(taxonomy.schema, 'b10x-ecosystem-families/v1');
  assert.deepEqual(taxonomy.families.map((family) => family.id), ['Foundation', 'Build', 'Services', 'Products']);
  assert.deepEqual(documentationFamilyOrder, taxonomy.families.map((family) => family.id));
  assert.deepEqual(taxonomy.families.map((family) => family.label), documentationFamilies.map((family) => family.label));
  assert.ok(taxonomy.families.every((family) => family.expectedMembers === undefined));
  const identifiers = new Set(taxonomy.families.map((family) => family.id));
  for (const family of taxonomy.families) {
    assert.ok(family.purpose.length > 40);
    assert.match(family.startRepository, /^[a-z0-9-]+$/);
    assert.ok(identifiers.has(family.next.family));
    assert.ok(family.next.label.length > 20);
    assert.equal(family.repositories, undefined);
  }
  assert.match(taxonomy.families.find((family) => family.id === 'Products').purpose, /active development.*credential-free review mode.*not as a production adoption promise/i);
});

test('the family contract derives current repository counts without freezing the production roster', () => {
  const membership = {
    Foundation: ['agentic-principles', 'aep', 'ess', 'research'],
    Build: ['agentide', 'agentplugins', 'docs-system', 'entity-runtime', 'harness', 'mcp', 'metaharness', 'substrate', 'worktree'],
    Services: ['aep-service', 'agent-platform', 'connectors', 'eventlog', 'identity', 'secrets', 'workflow', 'workspace'],
    Products: ['devcenter'],
  };
  const manifests = [{repository: {id: 'website'}, surfaces: [{source: {navigation: {label: 'Start', order: 0, sidebar: 'flat'}}}]}];
  for (const [group, repositories] of Object.entries(membership)) {
    for (const [order, repository] of repositories.entries()) {
      manifests.push({repository: {id: repository}, surfaces: [{source: {navigation: {label: repository, group, order, sidebar: 'autogenerated'}}}]});
    }
  }
  assert.deepEqual(assertDocumentationFamilyDistribution(manifests), {Foundation: 4, Build: 9, Services: 8, Products: 1});
});

test('global navigation stays sticky, uses gateway routes, and retains mobile touch sizing', async () => {
  const css = await readFile(path.join(root, 'src/css/custom.css'), 'utf8');
  const config = await readFile(path.join(root, 'docusaurus.config.ts'), 'utf8');
  const navbar = /\.navbar \{([^}]*)\}/s.exec(css)?.[1] ?? '';
  const navbarLayer = /\.navbar::before \{([^}]*)\}/s.exec(css)?.[1] ?? '';
  assert.match(navbar, /position: sticky/);
  assert.match(navbar, /z-index: var\(--ifm-z-index-fixed\)/);
  assert.match(navbar, /top: 0/);
  assert.doesNotMatch(navbar, /backdrop-filter/);
  assert.match(navbarLayer, /backdrop-filter: blur\(15px\)/);
  assert.match(css, /@media screen and \(max-width: 996px\)/);
  assert.doesNotMatch(css, /@media screen and \(max-width: 1100px\)/);
  assert.match(css, /\.navbar__toggle \{[^}]*min-width: 44px;[^}]*min-height: 44px;/s);
  const navbarConfig = config.slice(config.indexOf('navbar:'), config.indexOf('footer:'));
  assert.match(navbarConfig, /hideOnScroll: false/);
  assert.deepEqual([...navbarConfig.matchAll(/label: '([^']+)'/g)].map((match) => match[1]), ['Try', 'Learn', 'Build', 'Products', 'Docs', 'Search', 'GitHub']);
  assert.deepEqual(
    [...navbarConfig.matchAll(/\{to: '([^']+)', label: '(Try|Learn|Build|Products|Docs|Search)'/g)].map((match) => match[1]),
    ['/start/', '/learn/', '/build/', '/products/', '/docs/', '/search/'],
  );
  for (const gateway of ['start', 'learn', 'build', 'products']) {
    await readFile(path.join(root, 'src/pages', gateway, 'index.tsx'), 'utf8');
  }
  assert.match(config, /autoCollapseCategories: true/);
});

test('shared status/filter tokens remain unshadowed and footer copy meets WCAG AA contrast', async () => {
  const css = await readFile(path.join(root, 'src/css/custom.css'), 'utf8');
  assert.doesNotMatch(css, /--b10x-(?:ink|ink-raised|signal|warning|danger):/);
  assert.doesNotMatch(css, /background: var\(--b10x-ink-raised\)/);
  assert.match(css, /\.footer__copyright \{[^}]*color: #b3c0ca;/s);
  assert.ok(contrast('#b3c0ca', '#303846') >= 4.5);
});

test('discovery and profile views compose the shared presentation primitives', async () => {
  const files = await Promise.all([
    'src/pages/ecosystem.tsx',
    'src/pages/changes.tsx',
    'src/pages/search.tsx',
    'src/pages/releases.tsx',
    'src/components/EcosystemFamilyLanding.tsx',
    'src/components/ExperienceView.tsx',
    'src/components/ProjectProfile.tsx',
  ].map((file) => readFile(path.join(root, file), 'utf8')));
  const source = files.join('\n');
  for (const component of ['PageHeader', 'SectionHeader', 'CardGrid', 'ContentCard', 'SearchField', 'FilterChipGroup', 'FactGrid', 'Callout']) {
    assert.match(source, new RegExp(`<${component}\\b`), `${component} must be exercised by the Website`);
  }
  assert.doesNotMatch(source, /<input[^>]*type="search"/);
  assert.doesNotMatch(source, /data-active=/);
});

test('interactive API and ecosystem projections preserve one page landmark and heading hierarchy', async () => {
  const api = await readFile(path.join(root, 'src/components/ApiReference.tsx'), 'utf8');
  const ecosystem = await readFile(path.join(root, 'src/pages/ecosystem.tsx'), 'utf8');
  assert.doesNotMatch(api, /<main[\s>]/);
  assert.doesNotMatch(api, /<h1[\s>]/);
  assert.match(api, /<OpenApiReference[^>]*headingLevel=\{3\}/);
  assert.match(ecosystem, /<ProjectCard[\s\S]*?headingLevel=\{2\}/);
  assert.doesNotMatch(ecosystem, /EcosystemProjectCard/);
});

test('project profiles derive adoption, references, revisions, releases, and both relationship directions', async () => {
  const profile = await readFile(path.join(root, 'src/components/ProjectProfile.tsx'), 'utf8');
  const preparation = await readFile(path.join(root, 'scripts/prepare-site.mjs'), 'utf8');
  assert.match(profile, /<AdoptionCard surface=\{surface\} journey=\{primaryJourneyOf\(surface\)\}/);
  assert.match(profile, /surface\.source\.specifications/);
  assert.match(profile, /surface\.feeds/);
  assert.match(profile, /item\.external \? <a href=\{item\.url\}>/);
  assert.match(profile, /external: true/);
  assert.match(profile, /latestReleaseFor\(repository\)/);
  assert.match(profile, /ownedKeys\.has\(relationship\.target\)/);
  assert.match(profile, /relationship\.kind === 'supports' && relationship\.target === 'website\/docs'/);
  assert.match(profile, /title="Outgoing"/);
  assert.match(profile, /title="Incoming"/);
  assert.match(preparation, /path\.join\(ecosystem, `\$\{repository\}\.mdx`\)/);
  assert.match(preparation, /<ProjectProfile repository=/);
  assert.match(preparation, /if \(!isPresentedRelationship\(relationship\)\) continue/);
});

test('six audience-first experiences have ordered learn, do, and verify steps with explicit outcomes', async () => {
  const catalog = JSON.parse(await readFile(path.join(root, 'data/experiences.json'), 'utf8'));
  const presentation = JSON.parse(await readFile(path.join(root, 'data/experience-pages.json'), 'utf8'));
  assert.equal(catalog.schema, 'b10x-experiences/v1');
  assert.deepEqual(catalog.experiences.map((experience) => experience.id), [
    'try-spec-driven-development',
    'understand-safe-agentic-coding',
    'build-agent-systems',
    'evaluate-beyond10x-products',
    'deploy-operate-products',
    'contribute-maintain',
  ]);
  assert.ok(catalog.artifacts.length > 0);
  assert.ok(catalog.experiences.every((experience) => experience.adoptionPaths.length > 0 && experience.audiences.length > 0));
  assert.ok(catalog.experiences.flatMap((experience) => experience.adoptionPaths).every((path) => path.outcome.length > 60 && path.artifactIds.length > 0));
  assert.ok(presentation.pages.every((page) => catalog.experiences.find((experience) => experience.id === page.experienceId)?.adoptionPaths.some((path) => path.id === page.adoptionPathId)));
  assert.deepEqual(presentation.pages.map((page) => page.sections.map((section) => section.kind)), Array(6).fill(['learn', 'do', 'verify']));
  assert.ok(presentation.pages.flatMap((page) => page.sections).flatMap((section) => section.steps).every((step) => step.completion.length > 40));
  const view = await readFile(path.join(root, 'src/components/ExperienceView.tsx'), 'utf8');
  assert.match(view, /data-pagefind-filter="experience"/);
  assert.match(view, /Complete when/);
  assert.match(view, /Currently blocked/);
  assert.match(view, /this does not grant artifact access/);
  assert.match(view, /Search within this path/);
});

test('architecture requests full-size keyboard panning and a complete textual projection', async () => {
  const architecture = await readFile(path.join(root, 'src/pages/architecture.tsx'), 'utf8');
  assert.match(architecture, /<DependencyGraph[^>]*minWidth="112rem"/);
  assert.doesNotMatch(architecture, /swipe horizontally on touch/);
  assert.match(architecture, /open its complete text alternative/);
});

test('the homepage leads with the practitioner path and a concept-first alternative', async () => {
  const home = await readFile(path.join(root, 'src/pages/index.tsx'), 'utf8');
  assert.match(home, /Plan a governed change with Claude/);
  assert.match(home, /Learn safe agentic coding/);
  assert.match(home, /story still active/);
  assert.match(home, /does not complete implementation/);
  assert.doesNotMatch(home, /Ship with agents|complete a governed, spec-driven change/);
  assert.doesNotMatch(home, /EcosystemFamilyOrientation|EcosystemFamilyGateway/);
});

test('repository families stay in reference views instead of the practitioner homepage', async () => {
  const home = await readFile(path.join(root, 'src/pages/index.tsx'), 'utf8');
  const ecosystem = await readFile(path.join(root, 'src/pages/ecosystem.tsx'), 'utf8');
  const preparation = await readFile(path.join(root, 'scripts/prepare-site.mjs'), 'utf8');
  assert.doesNotMatch(home, /EcosystemFamilyOrientation|EcosystemFamilyGateway/);
  assert.match(preparation, /path\.join\(docs, 'index\.mdx'\)/);
  assert.match(preparation, /<EcosystemFamilyOrientation surfaces=/);
  assert.match(preparation, /<EcosystemFamilyGateway surfaces=/);
  assert.match(preparation, /<EcosystemFamilyLanding family=/);
  assert.match(ecosystem, /deriveEcosystemNavigation\(registry, \{familyOrder\}\)/);
  assert.match(ecosystem, /label="Ecosystem family"/);
  assert.match(ecosystem, /<FilterChipGroup/);
  assert.match(ecosystem, /surfaceNavigation\(surface\)\?\.group === family/);
  assert.match(ecosystem, /setJourney\([^\n]+: 'all'\)/);
  assert.match(ecosystem, /setFamily\([^\n]+: 'all'\)/);
});

test('family landings derive membership, adoption, availability, and the next boundary from shared contracts', async () => {
  const landing = await readFile(path.join(root, 'src/components/EcosystemFamilyLanding.tsx'), 'utf8');
  assert.match(landing, /surfaceNavigation\(surface\)\?\.group === family\.id/);
  assert.match(landing, /<AdoptionCard surface=\{start\}/);
  assert.match(landing, /Current availability/);
  assert.match(landing, /<StatusBadge maturity=\{start\.maturity\}/);
  assert.match(landing, /uniqueRepositories/);
  assert.match(landing, /to=\{`\/docs\$\{next\.slug\}`\}/);
});

function contrast(foreground, background) {
  const [lighter, darker] = [luminance(foreground), luminance(background)].sort((left, right) => right - left);
  return (lighter + 0.05) / (darker + 0.05);
}

function luminance(hex) {
  return [1, 3, 5]
    .map((offset) => Number.parseInt(hex.slice(offset, offset + 2), 16) / 255)
    .map((channel) => channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4)
    .reduce((total, channel, index) => total + channel * [0.2126, 0.7152, 0.0722][index], 0);
}
