import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import {buildApiCatalog, describeApiSpecification, renderApiCatalogLanding} from '../scripts/api-catalog.mjs';
import {assertDocumentationFamilyDistribution, documentationFamilies, documentationFamilyOrder, renderSidebars} from '../scripts/sidebar-contract.mjs';
import {normalizePassiveMarkdown, stripManagedRanges} from '../scripts/passive-markdown.mjs';

const root = path.resolve(import.meta.dirname, '..');

test('API discovery is derived from locked specification facts and repository manifests', () => {
  const repositories = [
    ['secrets', 'Secrets', 'Services', 'openapi'],
    ['aep-service', 'AEP Service', 'Services', 'openapi'],
    ['docs-system', 'Docs System', 'Build', 'json-schema'],
    ['devcenter', 'Devcenter', 'Products', 'openapi'],
  ];
  const specifications = repositories.map(([repository, displayName, , kind], index) => describeApiSpecification({
    document: kind === 'openapi'
      ? {openapi: '3.1.0', info: {title: `${displayName} API`, version: `1.0.${index}`}, paths: {'/ready': {get: {}}, '/items': {parameters: [], post: {}}}}
      : {title: 'Manifest schema', type: 'object', properties: {schema: {}, repository: {}}},
    file: {repository, sourcePath: 'contract.json', specificationId: 'contract', kind, route: `/api/${repository}/contract/`},
    manifest: {repository: {id: repository, displayName, url: `https://github.com/beyond10x/${repository}`}},
    commit: String(index).repeat(40),
  }));
  const catalog = buildApiCatalog(specifications);
  assert.equal(catalog.schema, 'b10x-public-api-catalog/v1');
  assert.deepEqual(catalog.repositories.map((repository) => repository.id), ['aep-service', 'devcenter', 'docs-system', 'secrets']);
  assert.equal(catalog.repositories.length, 4);
  assert.equal(catalog.repositories.find((repository) => repository.id === 'aep-service').specifications[0].operationCount, 2);
  assert.equal(catalog.repositories.find((repository) => repository.id === 'docs-system').specifications[0].propertyCount, 2);
  const landing = renderApiCatalogLanding();
  assert.match(landing, /<ApiCatalog catalog=\{catalog\} \/>/);
  assert.match(landing, /\/api-catalog\.json/);
});

test('rendered Markdown removes complete managed documentation ranges without mutating source bytes', () => {
  const source = [
    '# Public README',
    '',
    '<!-- b10x-docs:discovery:start -->',
    '## Documentation',
    '[Self link](https://example.invalid)',
    '<!-- b10x-docs:discovery:end -->',
    '',
    '<!-- b10x-docs:start -->',
    'Generated discovery copy.',
    '<!-- b10x-docs:end -->',
    '',
    '<!-- b10x-docs-operations:start -->',
    'Generated agent operations.',
    '<!-- b10x-docs-operations:end -->',
    '',
    '```md',
    '<!-- b10x-docs:start -->',
    'A documented marker example.',
    '<!-- b10x-docs:end -->',
    '```',
    '',
    '## Kept {#kept}',
  ].join('\n');
  const original = Buffer.from(source);
  const rendered = normalizePassiveMarkdown(source);
  assert.doesNotMatch(rendered, /Self link|Generated discovery copy|Generated agent operations/);
  assert.match(rendered, /A documented marker example/);
  assert.match(rendered, /<a id="kept"><\/a>\n## Kept/);
  assert.deepEqual(Buffer.from(source), original);
  assert.throws(() => stripManagedRanges('<!-- b10x-docs:start -->\nunclosed'), /not closed/);
  assert.throws(() => stripManagedRanges('<!-- b10x-docs:end -->'), /without a start/);
});

test('canonical navigation groups render as four collapsed documentation families', () => {
  const repositories = [
    ['principles', 'Principles', 'Foundation'],
    ['runtime', 'Runtime', 'Foundation'],
    ['harness', 'Harness', 'Build'],
    ['worktree', 'Worktree', 'Build'],
    ['identity', 'Identity', 'Services'],
    ['workflow', 'Workflow', 'Services'],
    ['devcenter', 'Devcenter', 'Products'],
  ];
  const registry = {surfaces: [
    {name: 'Start', kind: 'front-door', repository: {id: 'website'}},
    ...repositories.map(([id, name]) => ({name, repository: {id}})),
  ]};
  const manifests = repositories.map(([id, name, group], order) => ({
    repository: {id},
    surfaces: [{source: {navigation: {label: name, group, order, sidebar: 'autogenerated'}}}],
  })).concat([{repository: {id: 'website'}, surfaces: [{source: {navigation: {label: 'Start', order: 0, sidebar: 'flat'}}}]}]);
  const source = renderSidebars(registry, manifests);
  const document = JSON.parse(source.replace(/^module\.exports = /, '').replace(/;\n$/, ''));
  assert.equal(document.docs[1].label, 'Start');
  assert.deepEqual(document.docs[1].items, [{type: 'autogenerated', dirName: 'website'}]);
  const families = document.docs.slice(2);
  assert.deepEqual(families.map((family) => family.label), documentationFamilies.map((family) => family.label));
  assert.ok(families.every((family) => family.collapsed && family.link.type === 'doc'));
  assert.deepEqual(families.map((family) => family.link.id), ['families/foundations', 'families/build', 'families/services', 'families/products']);
  assert.ok(families.flatMap((family) => family.items).every((repository) => repository.collapsed));
  assert.deepEqual(
    families.flatMap((family) => family.items).flatMap((repository) => repository.items.map((item) => item.dirName)).sort(),
    repositories.map(([id]) => id).sort(),
  );
});

test('the authored family map explains purpose, start, and a valid cross-family next step without owning membership', async () => {
  const taxonomy = JSON.parse(await readFile(path.join(root, 'data/ecosystem-families.json'), 'utf8'));
  assert.equal(taxonomy.schema, 'b10x-ecosystem-families/v1');
  assert.deepEqual(taxonomy.families.map((family) => family.id), ['Foundation', 'Build', 'Services', 'Products']);
  assert.deepEqual(documentationFamilyOrder, taxonomy.families.map((family) => family.id));
  assert.deepEqual(taxonomy.families.map((family) => family.label), documentationFamilies.map((family) => family.label));
  assert.deepEqual(taxonomy.families.map((family) => family.expectedMembers), [4, 7, 7, 1]);
  const identifiers = new Set(taxonomy.families.map((family) => family.id));
  for (const family of taxonomy.families) {
    assert.ok(family.purpose.length > 40);
    assert.match(family.startRepository, /^[a-z0-9-]+$/);
    assert.ok(identifiers.has(family.next.family));
    assert.ok(family.next.label.length > 20);
    assert.equal(family.repositories, undefined);
  }
  assert.match(taxonomy.families.find((family) => family.id === 'Products').purpose, /active development.*credential-free review mode.*not as a production adoption promise/i);
});

test('the production family contract contains exactly 4 foundation, 7 build, 7 service, and 1 product repositories', () => {
  const membership = {
    Foundation: ['agentic-principles', 'aep', 'ess', 'research'],
    Build: ['agentplugins', 'docs-system', 'entity-runtime', 'harness', 'metaharness', 'substrate', 'worktree'],
    Services: ['aep-service', 'agent-platform', 'connectors', 'eventlog', 'identity', 'secrets', 'workflow'],
    Products: ['devcenter'],
  };
  const manifests = [{repository: {id: 'website'}, surfaces: [{source: {navigation: {label: 'Start', order: 0, sidebar: 'flat'}}}]}];
  for (const [group, repositories] of Object.entries(membership)) {
    for (const [order, repository] of repositories.entries()) {
      manifests.push({repository: {id: repository}, surfaces: [{source: {navigation: {label: repository, group, order, sidebar: 'autogenerated'}}}]});
    }
  }
  assert.deepEqual(assertDocumentationFamilyDistribution(manifests), {Foundation: 4, Build: 7, Services: 7, Products: 1});
});

test('mobile navigation filtering lives on a sibling layer and controls meet touch sizing', async () => {
  const css = await readFile(path.join(root, 'src/css/custom.css'), 'utf8');
  const config = await readFile(path.join(root, 'docusaurus.config.ts'), 'utf8');
  const navbar = /\.navbar \{([^}]*)\}/s.exec(css)?.[1] ?? '';
  const navbarLayer = /\.navbar::before \{([^}]*)\}/s.exec(css)?.[1] ?? '';
  assert.doesNotMatch(navbar, /backdrop-filter/);
  assert.match(navbarLayer, /backdrop-filter: blur\(15px\)/);
  assert.match(css, /\.navbar__toggle \{[^}]*min-width: 44px;[^}]*min-height: 44px;/s);
  const navbarConfig = config.slice(config.indexOf('navbar:'), config.indexOf('footer:'));
  assert.deepEqual([...navbarConfig.matchAll(/label: '([^']+)'/g)].map((match) => match[1]), ['Start', 'Explore', 'Docs', 'Changes', 'Search', 'GitHub']);
  assert.match(config, /autoCollapseCategories: true/);
});

test('shared status/filter tokens remain unshadowed and footer copy meets WCAG AA contrast', async () => {
  const css = await readFile(path.join(root, 'src/css/custom.css'), 'utf8');
  assert.doesNotMatch(css, /--b10x-(?:ink|ink-raised|signal|warning|danger):/);
  assert.doesNotMatch(css, /background: var\(--b10x-ink-raised\)/);
  assert.match(css, /\.footer__copyright \{[^}]*color: #b3c0ca;/s);
  assert.ok(contrast('#b3c0ca', '#303846') >= 4.5);
});

test('interactive API and ecosystem projections preserve one page landmark and heading hierarchy', async () => {
  const api = await readFile(path.join(root, 'src/components/ApiReference.tsx'), 'utf8');
  const ecosystem = await readFile(path.join(root, 'src/components/EcosystemProjectCard.tsx'), 'utf8');
  assert.doesNotMatch(api, /<main[\s>]/);
  assert.doesNotMatch(api, /<h1[\s>]/);
  assert.match(api, /<OpenApiReference[^>]*headingLevel=\{3\}/);
  assert.match(ecosystem, /<h2><a href=/);
  assert.doesNotMatch(ecosystem, /<h3>/);
});

test('project profiles derive adoption, references, revisions, releases, and both relationship directions', async () => {
  const profile = await readFile(path.join(root, 'src/components/ProjectProfile.tsx'), 'utf8');
  const preparation = await readFile(path.join(root, 'scripts/prepare-site.mjs'), 'utf8');
  assert.match(profile, /<AdoptionCard surface=\{surface\} journey=\{primaryJourneyOf\(surface\)\}/);
  assert.match(profile, /surface\.source\.specifications/);
  assert.match(profile, /surface\.feeds/);
  assert.match(profile, /item\.external \? <a href=\{item\.url\}>/);
  assert.match(profile, /external: true/);
  assert.match(profile, /latestReleaseFor\(repository\)/);
  assert.match(profile, /ownedKeys\.has\(relationship\.target\)/);
  assert.match(profile, /relationship\.kind === 'supports' && relationship\.target === 'website\/docs'/);
  assert.match(profile, /title="Outgoing"/);
  assert.match(profile, /title="Incoming"/);
  assert.match(preparation, /path\.join\(ecosystem, `\$\{repository\}\.mdx`\)/);
  assert.match(preparation, /<ProjectProfile repository=/);
  assert.match(preparation, /if \(!isPresentedRelationship\(relationship\)\) continue/);
});

test('all five adoption routes use one manifest-driven journey view with explicit primary and related roles', async () => {
  const catalog = JSON.parse(await readFile(path.join(root, 'data/journeys.json'), 'utf8'));
  assert.equal(catalog.schema, 'b10x-adoption-journeys/v1');
  assert.deepEqual(catalog.journeys.map((journey) => journey.id), ['understand', 'plan-work', 'specify', 'build-agents', 'operate-services']);
  const identifiers = new Set(catalog.journeys.map((journey) => journey.id));
  assert.ok(catalog.journeys.every((journey) => identifiers.has(journey.next) && journey.verification.length > 60));
  const view = await readFile(path.join(root, 'src/components/JourneyView.tsx'), 'utf8');
  assert.match(view, /primaryJourneyOf\(surface\) === journey/);
  assert.match(view, /surface\.journeys\.includes\(journey\) && primaryJourneyOf\(surface\) !== journey/);
  assert.match(view, /surface\.repository\.id !== 'website'/);
  assert.match(view, /<AdoptionCard surface=\{surface\} journey=\{journey\}/);
  assert.match(view, /Verification expectation/);
  for (const journey of catalog.journeys) {
    const page = await readFile(path.join(root, 'src/pages/journeys', `${journey.id}.mdx`), 'utf8');
    assert.match(page, /import JourneyView from '@site\/src\/components\/JourneyView';/);
    assert.match(page, new RegExp(`<JourneyView journey="${journey.id}" \/>`));
    assert.doesNotMatch(page, /See every project in this journey/);
  }
});

test('architecture requests full-size keyboard panning and a complete textual projection', async () => {
  const architecture = await readFile(path.join(root, 'src/pages/architecture.tsx'), 'utf8');
  assert.match(architecture, /<DependencyGraph[^>]*minWidth="112rem"/);
  assert.match(architecture, /swipe horizontally on touch/);
  assert.match(architecture, /open its complete text alternative/);
});

test('hero copy preserves its visual break without joining words for assistive technology', async () => {
  const home = await readFile(path.join(root, 'src/pages/index.tsx'), 'utf8');
  assert.match(home, /From a principle\{' '\}<br \/>/);
});

test('family orientation leads home while exhaustive discovery stays in docs and ecosystem filters', async () => {
  const home = await readFile(path.join(root, 'src/pages/index.tsx'), 'utf8');
  const ecosystem = await readFile(path.join(root, 'src/pages/ecosystem.tsx'), 'utf8');
  const preparation = await readFile(path.join(root, 'scripts/prepare-site.mjs'), 'utf8');
  assert.match(home, /<EcosystemFamilyOrientation surfaces=\{registry\.surfaces\}/);
  assert.doesNotMatch(home, /<EcosystemFamilyGateway/);
  assert.match(preparation, /path\.join\(docs, 'index\.mdx'\)/);
  assert.match(preparation, /<EcosystemFamilyOrientation surfaces=/);
  assert.match(preparation, /<EcosystemFamilyGateway surfaces=/);
  assert.match(preparation, /<EcosystemFamilyLanding family=/);
  assert.match(ecosystem, /deriveEcosystemNavigation\(registry, \{familyOrder\}\)/);
  assert.match(ecosystem, /Filter by ecosystem family/);
  assert.match(ecosystem, /surfaceNavigation\(surface\)\?\.group === family/);
  assert.match(ecosystem, /setJourney\([^\n]+: 'all'\)/);
  assert.match(ecosystem, /setFamily\([^\n]+: 'all'\)/);
});

test('family landings derive membership, adoption, availability, and the next boundary from shared contracts', async () => {
  const landing = await readFile(path.join(root, 'src/components/EcosystemFamilyLanding.tsx'), 'utf8');
  assert.match(landing, /surfaceNavigation\(surface\)\?\.group === family\.id/);
  assert.match(landing, /<AdoptionCard surface=\{start\}/);
  assert.match(landing, /Current availability/);
  assert.match(landing, /<StatusBadge maturity=\{start\.maturity\}/);
  assert.match(landing, /uniqueRepositories/);
  assert.match(landing, /to=\{`\/docs\$\{next\.slug\}`\}/);
});

function contrast(foreground, background) {
  const [lighter, darker] = [luminance(foreground), luminance(background)].sort((left, right) => right - left);
  return (lighter + 0.05) / (darker + 0.05);
}

function luminance(hex) {
  return [1, 3, 5]
    .map((offset) => Number.parseInt(hex.slice(offset, offset + 2), 16) / 255)
    .map((channel) => channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4)
    .reduce((total, channel, index) => total + channel * [0.2126, 0.7152, 0.0722][index], 0);
}
